_core:
  default_config_hash: FWyW0pDoSvPRtqOVlIbk4PxTLiS9S_Ng7zS1JOflWVE
enable: true
address: acalderonfake@bilbomatica.es
roles: {  }
allowed: ''
description: true
message: true
mailkeys: ''
mailkeys_skip: ''
whitelist: ''
