<?php
/**
 * @file
 * Code for the OIRA WS feature.
 */

include_once 'oira_ws.features.inc';

/**
 * Implements hook_services_request_postprocess_alter($controller, $args, &$result)
 */
function oira_ws_services_request_postprocess_alter($controller, $args, &$result) {
  if (isset($args[0]['view_name'], $args[0]['display_id']) && $args[0]['view_name'] == 'oira_ws' && $args[0]['display_id'] == 'tools_ws') {
    foreach ($result as $item) {
      $node = node_load($item->nid);
      $section_id = array_keys($node->workbench_access);
      $partner = oira_partner_by_section_id_load($section_id[0]);
      unset($item->nid);

      $item->author_id = $partner ? $partner->uuid : null;
      $item->author_name = $partner ? $partner->title : null;
      $item->author_logo = null;
      if ($partner && !empty($partner->field_logo[LANGUAGE_NONE][0]['uri'])) {
        $url = file_create_url($partner->field_logo[LANGUAGE_NONE][0]['uri']);
        $item->author_logo = $url ?: null;
      }
      if (!empty($item->co_authors)) {
        $co_authors = [];
        foreach ($item->co_authors as $id) {
          if (!empty($id['tid']) && $co_author_partner = oira_partner_by_section_id_load($id['tid'])) {
            $co_author = (object) array(
              'author_id' => $co_author_partner->uuid,
              'author_name' => $co_author_partner->title,
              'author_logo' => @file_create_url($co_author_partner->field_logo[LANGUAGE_NONE][0]['uri'])
            );
            $co_authors[] = $co_author;
          }
        }
        if (!empty($co_authors)) {
          $item->co_authors = $co_authors;
        } else {
          unset($item->co_authors);
        }
      } else {
        unset($item->co_authors);
      }
    }
  }
}
