<?php
/**
 * @file
 * Code for the Contact Us and FAQ feature.
 */

include_once 'napo_contact.features.inc';

/**
 * Implements hook_menu_alter().
 */
function napo_contact_menu_alter(&$items) {
  // Add access callback for Reorder episodes tab.
  $items['node/%/reorder-faqs']['access callback'] = 'napo_contact_reoder_faq_access_callback';
  $items['node/%/reorder-oira-faqs']['access callback'] = 'napo_contact_reoder_faq_access_callback';
  $items['contact']['access callback'] = FALSE;
}

/**
 * Implements hook_node_view().
 */
function napo_contact_node_view($node, $view_mode, $langcode) {
  // Redirect all wiki pages to thei full page on wiki site.
  if ($node->type == 'faq' && $view_mode == 'full' && user_is_anonymous()) {
    if (!empty($node->field_oira)) {
      drupal_goto('oira-faqs', array(), 301);
    }
    else {
      drupal_goto('faq', array(), 301);
    }
  }
}

/**
 * Access callback for Reorder episodes tab.
 */
function napo_contact_reoder_faq_access_callback($options) {
  // Run the default access callback.
  $access_callback = $options[0];
  $access_arguments = $options[1];
  $access = call_user_func_array($access_callback, $access_arguments);
  if (!$access) {
    return FALSE;
  }
  $node = node_load(arg(1));
  if ($node && $node->type == 'faq') {
    return TRUE;
  }
  return FALSE;
}
