<?php
/**
 * @file
 * Code for the Strategic documentation feature.
 */

include_once 'oira_strategic_documentation.features.inc';

/**
 * Implements hook_field_extra_fields_alter().
 */
function oira_strategic_documentation_field_extra_fields_alter(&$info) {
  $info['node']['strategic_documentation']['display']['related_partners'] = $info['node']['practical_tool']['display']['related_partners'];
  $info['node']['strategic_documentation']['display']['tools_see_more'] = $info['node']['practical_tool']['display']['tools_see_more'];
}

/**
 * Implements hook_node_presave().
 */
function oira_strategic_documentation_node_presave($node) {
  if ($node->type == 'strategic_documentation') {
    cache_clear_all(_hwc_practical_tool_related_partners_cid($node), 'cache');
  }
}