<?php
/**
 * @file
 * Code for the Strategic documentation feature.
 */

include_once 'oira_strategic_documentation.features.inc';


/**
 * Implements hook_form_alter().
 */
function oira_strategic_documentation_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'strategic_documentation_node_form':
      // Hide country - it's automatically added in oira_partner.module
      $form['field_country']['#access'] = FALSE;

      // TODO a validation server side.
//      $form['#validate'][] = 'oira_promotional_material_form_validate';

      $form['field_private_image']['#states'] = array(
        'required' => array(
          ':input[name="field_strategic_type[und]"]' => array('value' => 'photo'),
        ),
      );
      $form['field_private_file']['#states'] = array(
        'visible' => array(
          array(
            ':input[name*="field_strategic_type[und]"]' => array('value' => 'document'),
          ),
          array(
            ':input[name*="field_strategic_type[und]"]' => array('value' => 'visual'),
          ),
        ),
      );
      $form['field_link']['#states'] = array(
        'visible' => array(
          ':input[name*="field_strategic_type[und]"]' => array('value' => 'link'),
        ),
      );
      break;
  }
}
