<?php
/**
 * @file
 * Code for the Strategic documentation feature.
 */

include_once 'oira_strategic_documentation.features.inc';

/**
 * Implements hook_block_info().
 */
function oira_strategic_documentation_block_info() {
  $blocks = array();
  $blocks['oira_strategic_docs_listing'] = array(
    'info' => t('Strategic documentation listing'),
    'status' => 1,
    'region' => '-1',
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function oira_strategic_documentation_block_view($delta = '') {
  $block = [];
  switch ($delta) {
    case 'oira_strategic_docs_listing':
      module_load_include('inc', 'oira_strategic_documentation', 'oira_strategic_documentation.pages');
      // Re-use some functions from hwc_practical_tool module
      module_load_include('inc', 'hwc_practical_tool', 'hwc_practical_tool.pages');
      $block['content'] = drupal_get_form('oira_strategic_documentation_search_form');
      break;
  }
  return $block;
}
