_core:
  default_config_hash: GLswejPT_b3G9TtpI4NKwR1mhIB_-FnysNn9QKc-01w
general:
  page_cache_maximum_age: '3600'
  noise: ''
  debug: '0'
  logging: '0'
  secret: c8642046905a892ebbf72a4b20a55333bb133786eb9b51b53b22bbca132c5e99
  varnish_server: 'https://oiraproject.eu'
  varnish_purger: true
  purger_maintenance_mode: false
  grace: '10'
available:
  enable_cache: true
  authenticated_users: false
  esi: false
  esi_purge_user_blocks: false
  excluded_urls: ''
cache_control:
  anonymous: '/user/logout|must-revalidate, no-cache, private'
  authenticated: ''
