cache_control:
  anonymous: '/user/logout|must-revalidate, no-cache, private'
  authenticated: ''
_core:
  default_config_hash: GLswejPT_b3G9TtpI4NKwR1mhIB_-FnysNn9QKc-01w
general:
  varnish_purger: true
  varnish_server: 'https://oiraproject.eu'
  purger_maintenance_mode: false
  logging: '0'
  debug: '0'
  noise: ''
  secret: c8642046905a892ebbf72a4b20a55333bb133786eb9b51b53b22bbca132c5e99
  grace: '10'
  page_cache_maximum_age: '3600'
available:
  enable_cache: true
  authenticated_users: false
  esi: false
  esi_purge_user_blocks: false
  excluded_urls: ''
