_core:
  default_config_hash: hjgcuHpcsme6SW-7MKpZm3bhnR76f1yX2Y8Xe0STesw
drupalAcctProvisionServer: osha
ldapEntryProvisionServer: osha_write
drupalAcctProvisionTriggers:
  - drupal_on_login
  - drupal_on_update_create
ldapEntryProvisionTriggers:
  - ldap_on_update_create
orphanedDrupalAcctBehavior: user_cancel_block
orphanedCheckQty: 100
orphanedAccountCheckInterval: weekly
userConflictResolve: resolve
manualAccountConflict: conflict_associate
acctCreation: ldap_behaviour
disableAdminPasswordField: false
userUpdateCronQuery: none
userUpdateCronInterval: always
ldapUserSyncMappings: {  }
