<?php

/**
 * Change weight of the module for hook form alter.
 */
function oira_partner_update_7001() {
  db_update('system')
    ->fields(array('weight' => 10))
    ->condition('name', 'oira_partner', '=')
    ->execute();
}

function oira_partner_update_7002() {
  features_revert_module('oira_partner');
}

/**
 * Feature revert Sprint 5: NOW-272, NOW-273.
 */
function oira_partner_update_7003() {
  features_revert_module('oira_partner');
}
