tips:
  search-api-index-fields-label:
    label: Label
  search-api-index-fields-machine-name:
    label: 'Nume maşină'
  search-api-index-fields-type:
    label: Tip
  search-api-index-fields-submit:
    label: 'Save changes'
