<?php
/**
 * @file
 * Code for the Oira collaboration items feature.
 */

include_once 'oira_collaboration_items.features.inc';

/**
 * Implements hook_block_info().
 */
function oira_collaboration_items_block_info() {
  $blocks = array();

  $blocks['oira_collaboration_items'] = array(
    'info' => t('Collaboration documents search'),
    'status' => 1,
    'region' => '-1',
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function oira_collaboration_items_block_view($delta = '') {
  $block = array();
  if ($delta == 'oira_collaboration_items') {
    module_load_include('inc', 'oira_collaboration_items', 'oira_collaboration_items.pages');
    $block['content'] = drupal_get_form('oira_collaboration_items_form');
  }
  return $block;
}
