<?php

/**
 * Feature revert Sprint 5: NOW-267.
 */
function oira_promotional_material_update_7001() {
  features_revert_module('oira_promotional_material');
}

/**
 * Feature revert
 */
function oira_promotional_material_update_7002() {
  features_revert_module('oira_promotional_material');
}

/**
 * Feature revert: NOW-237
 */
function oira_promotional_material_update_7003() {
  features_revert_module('oira_promotional_material');
}
