<?php
/**
 * @file
 * Code for the OiRA Promotional material feature.
 */

include_once 'oira_promotional_material.features.inc';

/**
 * Implements hook_block_info().
 */
function oira_promotional_material_block_info() {
  $blocks = array();
  $blocks['oira_promotional_listing'] = array(
    'info' => t('Promotional materials listing'),
    'status' => 1,
    'region' => '-1',
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function oira_promotional_material_block_view($delta = '') {
  $block = [];
  switch ($delta) {
    case 'oira_promotional_listing':
      module_load_include('inc', 'oira_promotional_material', 'oira_promotional_material.pages');
      $block['content'] = drupal_get_form('oira_promotional_material_search_form');
      break;
  }
  return $block;
}
