<?php

/**
 * Feature revert: NOW-237.
 */
function oira_private_image_update_7001() {
  features_revert_module('oira_private_image');
}

/**
 * NOW-365.
 */
function oira_private_image_update_7002() {
  features_revert_module('oira_private_image');
}

/**
 * MDR-1344.
 */
function oira_private_image_update_7003() {
  features_revert_module('oira_private_image');
}

function oira_private_image_update_7004() {
  module_enable(['colorbox', 'osha_gallery']);
}
